stages:
  - test

automation-test-job:
  stage: test
  tags:
    - local
  script:
    - echo "Running tests..."
    - npm install
    - npm run test:ci
    - npx wdio run wdio.conf.ts --spec setoran.feature
  artifacts:
    paths:
      - envs
    expire_in: 1 hour  # File akan disimpan selama 1 jam