stages:
  - test

automation-test-job:
  stage: test
  tags:
    - local
  script:
    - echo "CI_COMMIT_BEFORE_SHA:string $CI_COMMIT_BEFORE_SHA"
    - echo "CI_COMMIT_SHA:string $CI_COMMIT_SHA"
    - echo "Checking for changed feature files..."
    - |
      # Menyimpan daftar file yang diubah dan mengubahnya menjadi array
      CHANGED_FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME...$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -- '*.feature')
      echo "Changed feature files: $CHANGED_FILES"

      # Mengonversi CHANGED_FILES menjadi format array
      if [ -n "$CHANGED_FILES" ]; then
        IFS=$'\n' read -rd '' -a FILE_ARRAY <<< "$CHANGED_FILES"
        echo "Running WebdriverIO tests for changed features..."
        npx wdio run wdio.conf.ts --spec "${FILE_ARRAY[@]}"
      else
        echo "No feature files changed. Skipping tests."
      fi

    - echo "Test execution completed."